apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gotk-components.yaml
  - gotk-sync.yaml
   # Include other YAML files for services and gateways
  - apps/metrics.yaml
  - apps/istio-gateway.yaml
  - apps/metrics-gateway.yaml
  - apps/product-gateway.yaml
  - apps/product.yaml
  - apps/ratings-gateway.yaml
  - apps/ratings.yaml
  - apps/reviews-gateway.yaml
  - apps/reviews.yaml
  - apps/server-info-gateway.yaml
  - apps/server-info.yaml
