version: '3.8'
services:
  product:
    build:
      context: .
      dockerfile: cmd/product/Dockerfile
    ports:
      - "8080:8080"

  ratings:
    build:
      context: .
      dockerfile: cmd/ratings/Dockerfile
    ports:
      - "8081:8080"

  reviews:
    build:
      context: .
      dockerfile: cmd/reviews/Dockerfile
    ports:
      - "8082:8080"

  server_info:
    build:
      context: .
      dockerfile: cmd/server_info/Dockerfile
    ports:
      - "50051:50051"

  metrics:
    build:
      context: .
      dockerfile: cmd/metrics/Dockerfile
    ports:
      - "8083:8080"

