version: '3.8'
services:
  product:
    build: ./product
    ports:
      - "8080:8080"

  ratings:
    build: ./ratings
    ports:
      - "8081:8080"

  reviews:
    build: ./reviews
    ports:
      - "8082:8080"

