apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metrics
  template:
    metadata:
      labels:
        app: metrics
    spec:
      containers:
        - name: metrics
          image: skeletondocker/istio-services:metrics-5a766963d6d1a9dc805a3c2c674beada2cf9f2eb
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: metrics
  namespace: default
spec:
  selector:
    app: metrics
  ports:
    - port: 8080
      name: http