apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metrics
  template:
    metadata:
      labels:
        app: metrics
    spec:
      containers:
        - name: metrics
          image: skeletondocker/istio-services:metrics-04150219df454cb9192926fda7fba33386ec76b0
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: metrics
  namespace: default
spec:
  selector:
    app: metrics
  ports:
    - port: 8080
      name: http