apiVersion: apps/v1
kind: Deployment
metadata:
  name: product
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
        - name: product
          image: skeletondocker/istio-services:product-5a766963d6d1a9dc805a3c2c674beada2cf9f2eb
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: product
  namespace: default
spec:
  selector:
    app: product
  ports:
    - port: 8080
      name: http