apiVersion: apps/v1
kind: Deployment
metadata:
  name: ratings
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ratings
  template:
    metadata:
      labels:
        app: ratings
    spec:
      containers:
        - name: ratings
          image: skeletondocker/istio-services:ratings-960bbf85390dde1c64899737a71ab4b1e015878d
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: ratings
  namespace: default
spec:
  selector:
    app: ratings
  ports:
    - port: 8080
      name: http