apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-info
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server-info
  template:
    metadata:
      labels:
        app: server-info
    spec:
      containers:
        - name: server-info
          image: skeletondocker/istio-services:server-info-6b1ea2d5f73efe170bad532fa948af21b37d1b75
          ports:
            - containerPort: 50051
              protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: server-info
  namespace: default
spec:
  selector:
    app: server-info
  ports:
    - port: 50051
      name: grpc