apiVersion: apps/v1
kind: Deployment
metadata:
  name: ratings
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ratings
  template:
    metadata:
      labels:
        app: ratings
    spec:
      containers:
        - name: ratings
          image: skeletondocker/istio-services:ratings-22cccd79d4a68701c7acda2685da33a7d95a5cdd
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: ratings
spec:
  selector:
    app: ratings
  ports:
    - port: 8080
      name: http