apiVersion: apps/v1
kind: Deployment
metadata:
  name: ratings
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ratings
  template:
    metadata:
      labels:
        app: ratings
    spec:
      containers:
        - name: ratings
          image: skeletondocker/istio-services:ratings-bcac052fe5e42185f4a797e674e58d6aee2e1a4e
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: ratings
spec:
  selector:
    app: ratings
  ports:
    - port: 8080
      name: http