apiVersion: apps/v1
kind: Deployment
metadata:
  name: reviews
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reviews
  template:
    metadata:
      labels:
        app: reviews
    spec:
      containers:
        - name: reviews
          image: skeletondocker/istio-services:reviews-6d16b9b5ac24ff141ec716bb0b42957824b9cbf7
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: reviews
spec:
  selector:
    app: reviews
  ports:
    - port: 8080
      name: http