name: Build and Push Microservices

on: [push, pull_request]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [product, ratings, reviews, server_info, metrics]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build and Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./cmd/${{ matrix.service }}/Dockerfile
          push: true
          tags: skeletondocker/istio-services:${{ matrix.service }}-${{ github.sha }}

      - name: Docker Images
        run: docker images

  update-k8s-manifests:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Update Image in Kubernetes Manifests
        run: |
          sed -i 's|skeletondocker/istio-services:product-[a-zA-Z0-9]*|skeletondocker/istio-services:product-${{ github.sha }}|g' ./platform/kube/flux-system/apps/*.yaml
          sed -i 's|skeletondocker/istio-services:ratings-[a-zA-Z0-9]*|skeletondocker/istio-services:ratings-${{ github.sha }}|g' ./platform/kube/flux-system/apps/*.yaml
          sed -i 's|skeletondocker/istio-services:reviews-[a-zA-Z0-9]*|skeletondocker/istio-services:reviews-${{ github.sha }}|g' ./platform/kube/flux-system/apps/*.yaml
          sed -i 's|skeletondocker/istio-services:server_info-[a-zA-Z0-9]*|skeletondocker/istio-services:server_info-${{ github.sha }}|g' ./platform/kube/flux-system/apps/*.yaml
          sed -i 's|skeletondocker/istio-services:metrics-[a-zA-Z0-9]*|skeletondocker/istio-services:metrics-${{ github.sha }}|g' ./platform/kube/flux-system/apps/*.yaml
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add ./platform/kube/*.yaml
          git commit -m "Update image ID to new_hash"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}